apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    'helm.sh/hook': pre-install,pre-upgrade
    'helm.sh/hook-weight': '004'
    'helm.sh/hook-delete-policy': before-hook-creation
type: Opaque
data:
  # These have to be set dynamically when executing helm install/upgrade
  DB_USER: {{ b64enc .Values.secrets.DB_USER }}
  DB_PASSWORD: {{ b64enc .Values.secrets.DB_PASSWORD }}
