# This file serves as an example agent configuration to interact with the
# docker compose environment.
#
# You should pass the following command line flags when running the agent
# locally and using this file:
#
#   -enable-features=integrations-next -config.expand-env -config.enable-read-api
#
# -enable-features=integrations-next is required as the file is configured for
# the integrations revamp.
#
# -config.expand-env is required to expand environment variables. Environment
# variables are used when running the agent inside of docker-compose to connect
# to the other services. When running the agent externally, the expressions will
# default to the appropriate values of the exposed ports.
#
# -config.enable-read-api is optional, but allows you to invoke the /-/config
# endpoint to examine the generated config.

server:
  log_level: debug

traces:
  configs:
  - name: default
    remote_write:
      - endpoint: ${TEMPO_HOST:-localhost:4317}
        insecure: true
    receivers:
      otlp:
        protocols:
          grpc:
